# Generated by Django 4.0.3 on 2022-03-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0001_User'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id_form', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('close_condition', models.CharField(choices=[('D', 'Date'), ('C', 'Users count')], max_length=1)),
                ('close_value', models.CharField(max_length=20)),
                ('is_close', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('items', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankiety.user')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ankiety.form')),
                ('responses', models.JSONField()),
            ],
        ),
    ]
