# Generated by Django 4.0.3 on 2022-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0003_chartssettings_alter_form_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
