# Generated by Django 4.0.3 on 2022-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0006_alter_form_created_at_alter_form_owner_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='items',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
