# Generated by Django 4.0.3 on 2022-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0007_alter_form_items_alter_form_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='is_close',
            new_name='is_closed',
        ),
        migrations.AlterField(
            model_name='form',
            name='close_condition',
            field=models.CharField(choices=[('N', 'No condition'), ('D', 'Date'), ('C', 'Users count')], default='N', max_length=1),
        ),
    ]
