# Generated by Django 4.0.3 on 2022-03-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0008_rename_is_close_form_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='close_value',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
