# Generated by Django 4.0.3 on 2022-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0010_form_close_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
